openapi : 3.0.0
info:
  title: PostHub
  description: This is a multi user blog platform.
  version: 1.0.1

servers:
  - url: http://localhost:5000/api
    description: localhost platform of our app.

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

    BearerAuth:
      type: http
      scheme: bearer